 # **🌍 GeoPython Marathon**

- **📅 课程名称**：Python基础语法
- **👨‍🏫 讲师**：董元彪
- **📅 课程时间**：2025年6月18日

<img src="image/授课封面.png"/>

[](python1.jpg)

<img src="image/python1.jpg" alt="图片描述" width="700" height="400"/>

<img src="image/python2.jpg" alt="图片描述" width="1200" height="800"/>

![示例图片](image/python3.jpg)

代码通过步骤1到python环境翻译成计算机能看懂的代码（二进制），

通过步骤2传入到计算机内部（cpu）计算，

通过步骤3将计算结果（二进制）传回python环境，翻译成10进制数，

通过步骤4传回编辑器，结果显示到控制台。

# 一、变量

Python 对变量名的要求并不苛刻，但为了让代码可读易懂，建议遵守以下原则：

1. 只能包含字母、数字和下划线（_），且不能以数字开头。根据PEP 8编码规范，建议使用小写字母命名变量，且单词间以下划线进行分隔，如fruit_name。

2. 见名知意：尽量让变量名体现变量用途，例如 age, price, user_name 等。避免使用拼音进行命名。

3. 使用蛇形命名法或驼峰式：如user_name（蛇形命名法）、ClassName(驼峰式)

4. 常量使用全大写字母：如NAME = "Alice" 。

5. 不与 Python 关键字冲突：如 if, else, for, while 等。

In [8]:
import keyword

print(keyword.kwlist)# 打印所有的Python关键字
print(len(keyword.kwlist))# Python关键字数量

# 输出
['False','None','True','__peg_parser__','and','as','assert','async','await','break','class','continue','def','del','elif','else','except','finally','for','from','global','if','import','in','is','lambda','nonlocal','not','or','pass','raise','return','try','while','with','yield']
36

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


36

# 二、常见数据类型
1.整数（int）：整数类型，用来表示不带小数点的数值，如 -1, 0, 10, 999，等等。

2.浮点数（float）：带小数点的数值类型，比如 3.14, 1.0, -2.5。在 Python 中，浮点数可以用来表示身高、体重、价格等需要小数点的数据。  

3.字符串（str）：字符串用来表示文本、字符或符号等。例如 "Hello", "这是一段中文"。字符串可以用单引号 '、双引号 " 或三引号 ''' 括起来。三引号 '''用来表示多行字符串。

4.布尔值（bool）：布尔值只有两个取值：True（真） 和 False（假）。常用于逻辑判断或条件判断的场景。  

In [9]:
# 定义各种类型的变量
age = 20# 整数
price = 12.5# 浮点数
student_name = "Alice" # 字符串
is_paid = False# 布尔

# 输出
print("年龄：", age)
print("价格：", price)
print("姓名：", student_name)
print("是否付款：", is_paid)

年龄： 20
价格： 12.5
姓名： Alice
是否付款： False
成绩： [85, 90, 78]
元组地址： ('City', 'Street', 123)
信息： {'name': 'Alice', 'age': 20, 'scores': [85, 90, 78]}


## 不同类型变量表示数值范围

1.整数

C语言提供了 short、int、long、long long 四种类型的整数，它们的长度依次递增，错误对数据进行赋值会导致数值溢出。

而 Python 则不同，它的原生整数不分类型，或者说它只有一种类型（可变类型）的整数。Python 整数的取值范围是无限的，不管多大或者多小的数字，Python 都能轻松处理。

In [2]:
n = 78
x = 8888888888888888
y = -77777777777777
print(n)
print(type(n))
print(x)
print(type(x))
print(y)
print(type(y))
 
#  x 是一个极大的数字，y 是一个很小的数字，Python 都能正确输出，不会发生溢出，这说明 Python 对整数的处理能力非常强大。
#不管对于多大或者多小的整数，Python 只用一种类型存储，就是 int。

78
<class 'int'>
8888888888888888
<class 'int'>
-77777777777777
<class 'int'>


使用其他库时的固定大小整数​​

若通过 array 模块或 numpy 等库使用固定大小整数（如 int32, int64），范围由字节数决定：

| 类型 | 字节数 | 范围 (含公式) | 示例值 |
| --- | --- | --- | --- |
| int8 | 1 | -2^7 到 2^7 - 1 (-128 到 127) | numpy.int8(127) |
| int16 | 2 | -2^15 到 2^15 - 1 (-32768 到 32767) | numpy.array('h', [30000]) |
| int32 | 4 | -2^31 到 2^31 - 1 (-2147483648 到 2147483647) | numpy.int32(109) |
| int64 | 8 | -2^63 到 2^63 - 1 (-9e18 到 9e18) | numpy.int64(1018) |

In [2]:
import numpy as np
x = np.int32(2147483647)  # 最大值
x += 1         
print(x)
# 溢出为 -2147483648（未定义行为）

-2147483648


C:\Users\DYB\AppData\Local\Temp\ipykernel_50152\2614899110.py:3: RuntimeWarning: overflow encountered in scalar add
  x += 1


2. 小数

Python 只有一种小数类型，就是 float ,​​双精度浮点数（64-bit double-precision）。C语言有两种小数类型，分别是 float 和 double：float能容纳的小数范围比较小，double 能容纳的小数范围比较大。

python 中的小数有两种书写形式：十进制形式、指数形式。

十进制形式：这种就是我们平时看到的小数形式，例如 34.6、346.0、0.346。书写小数时必须包含一个小数点，否则会被 Python 当作整数处理。

指数形式：aEn 或 aen。a 为尾数部分，是一个十进制数；n 为指数部分，是一个十进制整数；E或e是固定的字符，用于分割尾数部分和指数部分。整个表达式等价于 a×10n。


In [6]:
f1 = 12.5
f2 = 3.141592678123456789
f3 = 12e4
f4 = 1e308 * 2
f5 = float('nan')  # 表示非数值
print("f1value:", f1)
print("f1type:", type(f1))
print("f1value:", f2)
print("f1type:", type(f2))
print("f1value:", f3)
print("f1type:", type(f3))
print("f1value:", f4)
print("f1type:", type(f4))
print("f1value:", f5)
print("f1type:", type(f5))

f1value: 12.5
f1type: <class 'float'>
f1value: 3.1415926781234567
f1type: <class 'float'>
f1value: 120000.0
f1type: <class 'float'>
f1value: inf
f1type: <class 'float'>
f1value: nan
f1type: <class 'float'>


使用numpy库的固定大小整数​​

| 别名 | 位数 | 内存占用 | 数值范围 (绝对值) | 精度 (有效位) | 常见用途 |
| --- | --- | --- | --- | --- | --- |
| np.float16 | 16 | 2 字节 | ~5.96e-8 到 6.55e4 | ~3~4 位 | 深度学习、内存敏感场景 |
| np.float32 | 32 | 4 字节 | ~1.18e-38 到 3.4e38 | ~6~7 位 | 通用科学计算、GPU 加速 |
| np.float64 | 64 | 8 字节 | ~2.23e-308 到 1.79e308 | ~15~17 位 | 高精度计算、默认浮点类型 |
| np.float128 | 80/128 | 16 字节 | ~3.36e-4932 到 1.19e4932 | ~18~34 位 | 超高精度计算 (平台依赖) |

In [7]:
import numpy as np

arr = np.array([1.23, 4.56, 7.89], dtype=np.float32)
print(arr)
print("数据类型:", arr.dtype)

[1.23 4.56 7.89]
数据类型: float32


5.列表（list）：列表可以看作一个有序的数据“序列”，通过方括号 [ ] 表示。它可以存放任意类型的数据，甚至可以互相嵌套。列表中的元素通过索引（index）来访问，索引从 0 开始。列表是可变的（mutable），可以随时添加、删除或修改元素。  

6.元组（tuple）：与列表类似，但用小括号 ( ) 表示，且元组是不可变（immutable）的，一旦创建就不能修改其中的元素值。 
 
7.字典（dict）：字典用来存储“键-值对”（key-value pairs），形如 { key1: value1, key2: value2 }。它有点像“通讯录”，key 相当于姓名，value 相当于联系方式或其他信息。  

In [ ]:
scores = [85, 90, 78]# 列表
address = ("City", "Street", 123)# 元组
info = {
"name":student_name,
"age":age,
"scores":scores
}# 字典
print("成绩：", scores)
print("元组地址：", address)
print("信息：", info)

## 三、可变与不可变类型
1.不可变类型：整数、浮点数、字符串、元组等。这些对象一旦创建，内容就无法更改。不可被更改的意思不是无法被重新赋值，而是无法直接修改内存中存储的值，重新赋值后内存地址会发生变化。

2.可变类型：列表、字典、集合等。对象创建后，其内容可以被修改。

In [10]:
# 不可变对象
x = 10
print(id(x))  # 输出对象的内存地址
x += 1
print(id(x))  # 内存地址发生变化

# 可变对象
lst = [1, 2, 3]
print(id(lst))
lst.append(4)
print(id(lst))  # 内存地址不变


140736224990280
140736224990312
1719364244416
1719364244416


# 四、Python运算符分类
1. 算术运算符：+（加）, -（减）, *（乘）, /（除）, %（取余）, **（幂）, //（整除）

2. 赋值运算符：=, +=, -=, *=, /=, %=, **=, //=

3. 比较（关系）运算符：==, !=, >, <, >=, <=

4. 逻辑运算符：and（与）, or（或）, not（非）

5. 位运算符：&（按位与）, |（按位或）, ^（按位异或）, ~（按位取反）, <<（左移）, >>（右移）

6. 成员运算符：in, not in

7. 身份运算符：is, is not


In [12]:
# 代码示例：算术运算符
a = 10
b = 3

print("a + b =", a + b)   # 13
print("a - b =", a - b)   # 7
print("a * b =", a * b)   # 30
print("a / b =", a / b)   # 3.333...
print("a // b =", a // b) # 3
print("a % b =", a % b)   # 1
print("a ** b =", a ** b) # 1000


a + b = 13
a - b = 7
a * b = 30
a / b = 3.3333333333333335
a // b = 3
a % b = 1
a ** b = 1000


In [13]:
# 复合赋值运算符：+=（加后赋值）、-=（减后赋值）、*=（乘后赋值）、/=（除后赋值）、//=、%=、**=等。 它们的作用是：先进行运算，再把结果赋值给左侧变量。
x = 5

x += 3  # 相当于 x = x + 3
print(x)  # 8

x *= 2  # 相当于 x = x * 2
print(x)  # 16

x -= 10 # 相当于 x = x - 10
print(x)  # 6


8
16
6


## 4.1 比较（关系）运算符
| 运算符 | 描述 | 示例 | 结果 |
| --- | --- | --- | --- |
| == | 等于 | 5 == 5 | True |
| != | 不等于 | 5 != 6 | True |
| > | 大于 | 7 > 3 | True |
| < | 小于 | 2 < 8 | True |
| >= | 大于等于 | 4 >= 4 | True |
| <= | 小于等于 | 3 <= 6 | True |


In [11]:
x = 7
y = 10

print("x == y ?", x == y)  # False
print("x != y ?", x != y)  # True
print("x > y ?", x > y)    # False
print("x < y ?", x < y)    # True
print("x >= y ?", x >= y)  # False
print("x <= y ?", x <= y)  # True


x == y ? False
x != y ? True
x > y ? False
x < y ? True
x >= y ? False
x <= y ? True


## 4.2 逻辑运算符
1.and（与）：当且仅当所有条件都为 True 时，最终结果才为 True。

2.or（或）：只要有一个条件为 True，最终结果就是 True。

3.not（非）：将布尔值取反，True 变 False，False 变 True。

In [ ]:
age = 20
is_student = True

# 条件 1：年龄必须 >= 18
# 条件 2：必须是学生
print("是否满足优惠条件？", (age >= 18) and is_student)  # True

score = 85
print("是否优秀？", (score > 90) or (score == 85))      # True

is_raining = False
print("今天不下雨吗？", not is_raining)                # True


是否满足优惠条件？ True
是否优秀？ True
今天不下雨吗？ True


## 4.3 位运算符

| 运算符 | 描述 | 示例 | 结果 (二进制解释) |
| --- | --- | --- | --- |
| & | 按位与 | 5 & 3 | 1 (0101 & 0011 = 0001) |
| \| | 按位或 | 5 \| 3 | 7 (0101 & 0011 = 0111) |
| ^ | 按位异或 | 5 ^ 3 | 6 (0101 ^ 0011 = 0110) |
| ~ | 按位取反 | ~5 | -6 |
| << | 左移 | 3 << 1 | 6 (0011 << 1 = 0110) |
| >> | 右移 | 6 >> 1 | 3 (0110 >> 1 = 0011) |

Note: 

按位与：两个数字的每一个二进制位进行比较，只有对应的两个位都是1，结果才是1，否则为0。

按位或：两个数字的每一个二进制位进行比较，只要有一个是1，结果就是1。

按位异或：两个数字的每一个二进制位进行比较，当两个位不同时（一个0，一个1），结果才是1。

按位取反：将数字的每一个二进制位取反（0变1，1变0）。

左移：将数字的二进制位整体向左移动，右侧补0。相当于 乘以2的n次方（比如左移1位≈×2，左移2位≈×4）。
右移：将数字的二进制位整体向右移动，左侧补0（正数）。相当于 除以2的n次方并取整（比如右移1位≈÷2）。

# 4.4 综合示例：小计算器

演示如何让用户输入两个数字和一个运算符，然后输出计算结果。这里会用到 算术运算符、比较运算符、if 语句 等多方面的知识。

In [2]:
def simple_calculator():
    print("欢迎使用简易计算器！")
    num1 = float(input("请输入第一个数字: "))
    op = input("请输入运算符 (+, -, *, /): ")
    num2 = float(input("请输入第二个数字: "))

    if op == '+':
        result = num1 + num2
    elif op == '-':
        result = num1 - num2
    elif op == '*':
        result = num1 * num2
    elif op == '/':
        # 加一个判断，避免除以零
        if num2 == 0:
            print("错误：除数不能为 0！")
            return  # 结束函数
        else:
            result = num1 / num2
    else:
        print("错误：运算符无效！")
        return

    print("计算结果：", result)

# 调用函数
simple_calculator()


欢迎使用简易计算器！
计算结果： 180.0


# 五、列表（List）和元组（Tuple）

| 特性 | 列表 (List) | 元组 (Tuple) |
|------|------------|------------|
| 有序性 | 有序 | 有序 |
| 可变性 | 可变 | 不可变 |
| 表示方式 | [ ] | ( ) |
| 元素类型 | 任意类型 | 任意类型 |
| 使用场景 | 需要修改数据 | 数据固定不变 |

## 5.1 创建列表和元组

In [4]:

# 空列表
my_list = []

# 含有元素的列表
fruits = ["apple", "banana", "orange"]
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", True, 3.14]

text = "hello"
char_list = list(text)  # ["h", "e", "l", "l", "o"]

# 空元组
my_tuple = ()

# 含有元素的元组
colors = ("red", "green", "blue")
numbers_tuple = (1, 2, 3)
mixed_tuple = (1, "test", False)

text = "hello"
char_tuple = tuple(text)  # ('h', 'e', 'l', 'l', 'o')

# 特别注意：如果元组只有一个元素，必须加个逗号，比如 (5,)，不然 Python 会把它当作普通的整数表达式处理。

## 5.2 列表访问与切片

无论列表还是元组，都能像字符串一样，通过索引（index）或切片（slice）来访问或获取其元素。

In [ ]:
fruits = ["apple", "banana", "orange"]
print(fruits[0])   # apple
print(fruits[1])   # banana
print(fruits[-1])  # orange（倒数第一个）

fruits = ["apple", "banana", "orange", "grape", "pear"]
# 从索引 1（含）到索引 3（不含），得到["banana", "orange"]
slice_fruits = fruits[1:3]

# 从开头到索引 2（不含）
print(fruits[:2])  # ["apple", "banana"]

# 从索引 2 到末尾
print(fruits[2:])  # ["orange", "grape", "pear"]

# 步长为2，隔一个取一个
print(fruits[::2]) # ["apple", "orange", "pear"]


## 5.3 列表的增删查改

1.增加

append(value)：在列表末尾添加一个元素；

insert(index, value)：在指定位置插入元素；

extend(other_list)：将另一个可迭代对象中的所有元素添加到列表末尾



In [8]:
fruits = ["apple", "banana"]
fruits.append("orange")
print(fruits)  # ["apple", "banana", "orange"]

fruits = ["apple", "banana", "orange"]
fruits.insert(1, "grape")
print(fruits)  # ["apple", "grape", "banana", "orange"]

fruits = ["apple", "banana"]
more_fruits = ["peach", "pear"]
fruits.extend(more_fruits)
print(fruits)  # ["apple", "banana", "peach", "pear"]

['apple', 'banana', 'orange']
['apple', 'grape', 'banana', 'orange']
['apple', 'banana', 'peach', 'pear']


2.删除

remove(value)：根据具体值来删除第一个匹配的元素；

pop(index=-1)：根据索引删除并返回该元素（默认删除最后一个）；

del 语句：通过索引或切片删除；


In [9]:
fruits = ["apple", "banana", "banana", "orange"]
fruits.remove("banana")
print(fruits)  # ["apple", "banana", "orange"]

fruits = ["apple", "banana", "orange"]
last_fruit = fruits.pop()  # 如果不填参数, 默认删最后一个
print(last_fruit)  # "orange"
print(fruits)      # ["apple", "banana"]

first_fruit = fruits.pop(0)
print(first_fruit) # "apple"
print(fruits)      # ["banana"]

fruits = ["apple", "banana", "orange"]
del fruits[1]       # 删除索引1 (banana)
print(fruits)       # ["apple", "orange"]

fruits = ["apple", "banana", "orange", "pear"]
del fruits[1:3]     # 删除 banana 和 orange
print(fruits)       # ["apple", "pear"]

['apple', 'banana', 'orange']
orange
['apple', 'banana']
apple
['banana']
['apple', 'orange']
['apple', 'pear']


3. 修改

通过索引修改元素

4. 查询与其他操作

len(list)：获取列表长度；

in 和 not in：检查元素是否在列表中；

sort()：就地排序，sorted()：返回新的排序列表

In [10]:
fruits = ["apple", "banana", "orange"]
fruits[1] = "grape"
print(fruits)  # ["apple", "grape", "orange"]

scores = [85, 92, 78]
print(len(scores))  # 输出：3

fruits = ["apple", "banana", "orange"]
print("apple" in fruits)  # True
print("grape" not in fruits)  # True

scores = [85, 92, 78]
print(sorted(scores))  # [78, 85, 92]


['apple', 'grape', 'orange']
3
True
True
[78, 85, 92]


# 六、条件判断、条件表达式与布尔值

1.if: 判断是否满足某个条件；

2.if:else: 在满足或不满足条件的情况下分别处理；

3.if:elif:else: 适合多重分支，只要其中一条条件满足，后面就不再继续判断；

4.嵌套if 在一条 if 中再写 if，但要注意可读性和缩进。

5.条件表达式通常由比较运算符（例如 >, <, >=, <=, ==, !=）或逻辑运算符（and, or, not）组成，最终会产生一个布尔值 True 或 False。

6.变量 = 表达式1 if 条件 else 表达式2

In [3]:
age = int(input("请输入你的年龄："))
message = "成年人" if age >= 18 else "未成年人"
print(f"你是{message}。")

你是未成年人。


# 七、循环结构和循环控制语句

在大多数场景下，我们都需要重复执行某些操作。比方说：计算 1 到 100 的整数和；

批量处理一组文件；

让程序持续等待用户输入，直到满足退出条件。

如果没有循环，我们只能像流水线一样把相同的代码一遍遍复制粘贴，既笨拙又容易犯错。循环给了我们一个简洁且自动化的方案，只要把要做的事情放在循环体里，程序便能按照需求重复执行，大大提升效率！

## 7.1 for循环

在 Python 中，for 循环通常用来遍历“可迭代对象”（比如列表、元组、字符串、range 等）。它的基本格式是：

for 变量 in 可迭代对象:

&emsp;在循环体中，针对每次迭代的 "变量" 做相应的操作

In [1]:
fruits = ["apple", "banana", "orange"]
for fruit in fruits:
    print("I like", fruit)

I like apple
I like banana
I like orange


## 7.2 使用 range() 生成数字序列

如果我们想循环执行固定次数，一种常见方法是结合 range() 函数来使用。range(n) 会生成从 0 到 n-1 的整数序列。

In [2]:
for i in range(5):
    print(i)

# 从1到10（不含10），步长为2
for num in range(1, 10, 2):
    print(num)


0
1
2
3
4
1
3
5
7
9


## 7.3 while 循环

while 条件表达式:

&emsp;只要条件表达式为True，就持续执行这个代码块
    
 &emsp;当条件表达式为False，循环结束
    

In [3]:
sum_value = 0
n = 1

while n <= 100:
    sum_value += n
    n += 1

print("1 到 100 的和是:", sum_value)


1 到 100 的和是: 5050


## 7.4 循环控制语句：break、continue、else

1.break 语句: break 用于立即终止当前循环。比如我们想让用户猜数字，如果猜对就结束循环

2.continue 语句 continue 会跳过当前循环迭代，直接进入下一次循环。一般用来忽略某些特殊情况：

3.else与循环 Python 允许在 for 或 while 循环后面写 else，只有当循环没有被 break 或异常跳出时，才会执行 else 块。


In [4]:
secret = 7
while True:
    guess = int(input("猜一个数字(1-10):"))
    if guess == secret:
        print("恭喜你，猜对了！")
        break  # 猜对就退出循环
    else:
        print("不对哦，再试试")


不对哦，再试试
恭喜你，猜对了！


In [5]:
for i in range(1, 6):
    if i == 3:
        continue  # 跳过 i=3 这次循环
    print(i)


1
2
4
5


In [6]:
numbers = [1, 2, 3, 4, 5]
target = 3

for num in numbers:
    if num == target:
        print("找到目标数字:", target)
        break
else:
    print("没有找到目标数字")

找到目标数字: 3


# 八、函数

你要在不同地方反复实现同样的计算逻辑，或者同一段代码在项目的很多部分都会用到。如果我们只是拷贝粘贴这段代码，显然既繁琐又容易出错。函数就好比一个“代码片段的封装单元”，你可以：编写一次逻辑处理，之后随时调用它来重复使用；在需要时只改动一处函数定义，就能影响所有调用的地方，更好维护；让程序结构更清晰明了，避免“千行代码挤在一起”的混乱。换句话说，函数就像生活中的“厨具”或“工具”，当你需要“切菜”时，就调用“切菜器”；当你需要“搅拌”时，就调用“搅拌器”。这大大简化了我们的日常操作。函数的使用可以提高代码的可重用性和可维护性。

In [ ]:
#定义函数
def 函数名(参数1, 参数2, ...):
    """
    可选的文档字符串，用来简要说明函数用途。
    """
    # 函数体: 处理逻辑、计算过程
    # ...
    return 返回值


1.函数名：遵循标识符规则，尽量做到“见名知意”，如 calculate_sum、greet_user 

2.参数列表（可选）如果函数需要外部信息，就通过参数传入。有多个参数时用逗号分隔，没有参数时可留空。

3.文档字符串实现具体功能的代码块。

4.return（可选）用于将结果返回给调用者。不写 return，默认返回 None。

## 8.1 形式参数和实际参数

1.形参（Parameter，也叫形式参数）

当你在定义一个函数时，写在函数括号里的那些“占位符”。它们只是名称或符号，并没有具体数值，表示将来会传进来什么数据

2.实参（Argument，也叫实际参数）

当你在调用函数时，真正传给函数的值。这个值会被传递给对应的形参。

定义函数时，需要声明形参，用来说明函数打算接收哪些“类型”或“数量”的数据。调用函数时，必须提供和形参对应数量、类型或顺序的实参，否则函数无法正确执行。这就像先在信封上预留一个收件人名字的位置（形参），等真正邮寄时再往里面写上你想寄给谁（实参）。

In [1]:
def greet(name):
   print(f"Hello,{name}!")

greet("Alice")

# 这里的 "Alice" 就是实参（实际传入的参数）。执行时，name（形参）就会得到 "Alice" 这个值。


Hello,Alice!


## 8.2 可变长度参数

如果我们想要一个函数能够接收不确定数量的参数，例如你不知道用户会给这个函数传 1 个值，还是 10 个值呢？这时就需要 可变长度参数。

*args —— 可变数量的“位置参数”当你在函数定义里写 *args 时，就表示这函数可以接收任意数量的“位置实参”。

注意：*args 只是一个习惯写法，args 不一定要叫这个名字，但业界默认都写 *args，这样大家都能看懂。

In [2]:
def sum_numbers(*args):
    total = 0
    for num in args:  # args 是一个“元组”
        total += num
    return total

print(sum_numbers(1, 2, 3, 4)) 
print(sum_numbers(5, 10))     


10
15


## 8.3 关键字参数

**kwargs 就用来接收一堆“带名字”的参数（关键字参数）。在函数定义里写 **kwargs，就意味着：这个函数可以接收任意数量的关键字实参，并且它们会被装进一个 “字典（dict）” 里。


In [3]:
def print_info(**kwargs):
    print(kwargs)
    for key, value in kwargs.items():
        print(f"{key} -> {value}")

print_info(name="Alice", age=25, city="Beijing")

{'name': 'Alice', 'age': 25, 'city': 'Beijing'}
name -> Alice
age -> 25
city -> Beijing


In [4]:
def my_func(*args, **kwargs):
    print("args:", args)
    print("kwargs:", kwargs)

my_func(1, 2, 3, name="Alice", age=25)

args: (1, 2, 3)
kwargs: {'name': 'Alice', 'age': 25}


# 九、字典

一种键-值（key-value）映射的可变容器，使用 {} 或 dict() 创建。

常见操作：

1.访问 / 修改： my_dict[key]

2.删除： del my_dict[key], my_dict.pop(key)

3.遍历： keys(), values(), items()

4.更新： update(), 合并运算符 | （Python 3.9+）

5.注意点若 key 不存在而用 my_dict[key] 访问，会抛 KeyError；可以用 my_dict.get(key, 默认值) 更安全地访问；字典的 key 必须是可哈希对象（如字符串、整数、元组等），列表等可变对象不能作为 key。

In [5]:
# 建一个学生信息字典，包含姓名、年龄、成绩等；添加新字段；使用 items() 遍历查看所有键值对
def manage_student():
    student = {
        "name": "Alice",
        "age": 18,
        "scores": {"math": 90, "english": 85}
    }

    # 访问
    print("姓名:", student["name"])
    print("数学成绩:", student["scores"]["math"])

    # 修改
    student["age"] = 19
    student["scores"]["english"] = 88

    # 新增
    student["major"] = "Computer Science"

    # 遍历查看结果
    for key, value in student.items():
        print(key, ":", value)

manage_student()


姓名: Alice
数学成绩: 90
name : Alice
age : 19
scores : {'math': 90, 'english': 88}
major : Computer Science


# 十、类与对象

面向对象的思想：把可以独立存在、并具有一定属性和行为的东西，抽象成对象（Object），让对象和对象之间通过交互来完成整体需求。

类（Class）：相当于模板或蓝图，定义了对象该拥有什么属性、能做什么方法；

对象（Object/Instance）：基于类创建出来的具体实体，拥有类定义的属性与方法；

In [ ]:

# class 类名:
# 初始化方法(构造函数), 用来创建并初始化对象

# class 类名:
    # 初始化方法(构造函数), 用来创建并初始化对象
    # def __init__(self, 属性1, 属性2, ...):
        # self.属性1 = 属性1
        # self.属性2 = 属性2
        # ...

    # 类的方法
    # def 方法名(self, 参数):
        # self 代表调用这个方法的那一个对象
        # 在这里写实现逻辑
        # ...
        # pass


In [3]:
class Student:
    def __init__(self, name, age, student_id):
        # 初始化属性
        self.name = name
        self.age = age
        self.student_id = student_id

    def introduce(self):
        # 在方法里可以使用 self 访问对象属性
        print(f"我叫{self.name}，今年{self.age}岁，学号是{self.student_id}。")

    def choose_course(self, course_name):
        print(f"{self.name} 同学选择了课程：{course_name}")


In [4]:
student1 = Student("Alice", 20, "2023001")
student2 = Student("Bob", 19, "2023002")

# 访问属性
print(student1.name)   # Alice
print(student2.age)    # 19

# 调用方法
student1.introduce()
student2.choose_course("Python编程")


Alice
19
我叫Alice，今年20岁，学号是2023001。
Bob 同学选择了课程：Python编程


__init__ 方法：初始化对象属性，当你创建对象时自动执行；

self 代表当前对象，一定要出现在方法的第一个参数位置，以访问该对象的属性或调用其方法；

面向对象能让我们的代码更好地表现真实世界事物，使程序结构更清晰，更易维护和扩展。

## 10.1 属性

属性（Attributes）是指对象或类中用于存储数据的变量。根据定义位置和作用域的不同，属性可以分为"实例属性"和"类属性"。

"实例属性"是在对象层面上定义，属于“某个具体对象”的数据。通过在构造函数（__init__ 方法）中将参数赋值给 self 来实现。

"类属性"是在类层面上定义，属于“整个类”共享的数据。在类体内、__init__ 方法之外直接赋值。

In [5]:
class Car:
    wheel_count = 4   # 类属性

    def __init__(self, brand, color):
        self.brand = brand  # 实例属性：品牌
        self.color = color  # 实例属性：颜色

my_car = Car('迈巴赫', '黑色')
my_car2 = Car('比亚迪', '白色')

print(f"my_car 的品牌是：{my_car.brand}，颜色是：{my_car.color}, 车轮数量是：{my_car.wheel_count}")
print(f"my_car2 的品牌是：{my_car2.brand}，颜色是：{my_car2.color}, 车轮数量是：{my_car2.wheel_count}")

# 修改类属性
Car.wheel_count = 6
print(f"my_car 的品牌是：{my_car.brand}，颜色是：{my_car.color}, 车轮数量是：{my_car.wheel_count}")
print(f"my_car2 的品牌是：{my_car2.brand}，颜色是：{my_car2.color}, 车轮数量是：{my_car2.wheel_count}")

# 对实例的类属性进行修改
my_car.wheel_count = 8
print(f"my_car 的品牌是：{my_car.brand}，颜色是：{my_car.color}, 车轮数量是：{my_car.wheel_count}")
print(f"my_car2 的品牌是：{my_car2.brand}，颜色是：{my_car2.color}, 车轮数量是：{my_car2.wheel_count}")

# 如果在类层面修改了类属性的值，所有对象在访问时会受到影响；但如果某个对象对同名属性进行“重写”，就会在这个对象上生成同名的实例属性，从而与类属性区分开来。

my_car 的品牌是：迈巴赫，颜色是：黑色, 车轮数量是：4
my_car2 的品牌是：比亚迪，颜色是：白色, 车轮数量是：4
my_car 的品牌是：迈巴赫，颜色是：黑色, 车轮数量是：6
my_car2 的品牌是：比亚迪，颜色是：白色, 车轮数量是：6
my_car 的品牌是：迈巴赫，颜色是：黑色, 车轮数量是：8
my_car2 的品牌是：比亚迪，颜色是：白色, 车轮数量是：6


## 10.2 方法

方法是定义在类内部的函数，用来描述对象（或类）可以执行的操作或行为。根据其使用场景和第一个参数的不同，我们通常将方法分为三种：实例方法（instance method）、类方法（class method）和静态方法（static method）。

实例方法：在类中定义的普通方法，第一个参数默认是 self（表示方法所属的那个对象本身）。

类方法：需要使用 @classmethod 装饰器，第一个参数约定为 cls（表示方法所属的那个“类”本身）。

静态方法：需要使用 @staticmethod 装饰器，不需要 self 或 cls 这类特殊参数。

实例方法适合处理具体对象的操作，最常见、最常用。

In [6]:
# 实例方法
class Car:
    def __init__(self, brand, color):
        self.brand = brand
        self.color = color

    def start(self):
        print(f"{self.brand}已经启动！")

    def uphill(self):
        print(f"{self.brand}上山了！")

my_car = Car("AE86", "黑白色")
my_car.start()
my_car.uphill()

AE86已经启动！
AE86上山了！


In [7]:
# 类方法

class Student:
    school = "青春学园"# 类属性，所有 Student 对象共享

    def __init__(self, name, age):
        self.name = name
        self.age = age

    @classmethod
    def change_school(cls, new_school):
        cls.school = new_school  # 修改类属性

    def say_hello(self):
        print(f"我是{self.name}，{Student.school}的学生。")


student1 = Student("越前龙马", 13)
student1.say_hello()

Student.change_school("不动峰")
student1.say_hello()


我是越前龙马，青春学园的学生。
我是越前龙马，不动峰的学生。


In [8]:
# 静态方法
class Student:
    @staticmethod
    def calc_average(*scores):
        total = sum(scores)
        return total / len(scores) if scores else 0

# 静态方法的调用既可以用 "类名.方法名()" 的方式，也可以用 "对象.方法名()"。
avg = Student.calc_average(80, 90, 85)
print(avg)  # 输出: 85.0

stu = Student()
avg = stu.calc_average(80, 90, 85)
print(avg)  # 输出: 85.0

85.0
85.0


| 方法类型 | 第一个参数 | 访问实例属性 | 访问类属性 | 调用方式 | 常见用途 |
| -------- | ---------- | ------------ | ---------- | -------- | -------- |
| 实例方法 | self | 是 | 能(需用类名或self.class) | 对象.实例方法() | 操作或修改当前对象数据、业务逻辑 |
| 类方法 | cls | 否 | 是 | 类名.类方法() 或对象.类方法() | 修改类属性、生成新实例、类级别操作 |
| 静态方法 | 无 | 否 | 否 | 类名.静态方法() 或对象.静态方法() | 类相关的工具函数或通用功能 |

## 10.3 构造函数

在 Python 里，我们使用一个名叫 __init__ 的特殊方法来创建构造函数。当写 obj = 类名(参数...) 时，Python在内部先创建一个新的对象，然后自动调用 __init__(obj, 参数...) 来进行属性初始化或其他必要操作。你不需要手动调用 __init__，也不需要返回对象，这个过程由Python的机制完成。

构造函数通常用来：

设置属性初始值：如上例中的 brand、color。

完成必要的初始化逻辑：比如打开一个文件、建立数据库连接、检查某些输入是否合法等（当然要小心避免“繁重”操作）。

In [9]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        print(f"已创建学生：{self.name}, 年龄 {self.age}")

    def study(self, subject):
        print(f"{self.name} 正在学习 {subject} ...")

# 使用构造函数创建对象
stu1 = Student("茂木夏树", 18)
stu2 = Student("藤原拓海", 18)

# 调用方法
stu1.study("Python 基础")
stu2.study("高等数学")


已创建学生：茂木夏树, 年龄 18
已创建学生：藤原拓海, 年龄 18
茂木夏树 正在学习 Python 基础 ...
藤原拓海 正在学习 高等数学 ...


## 10.4 继承和多态

但随着程序的复杂度增加，我们需要更高级的工具来组织和管理代码，这就是继承和多态。继承和多态的作用：

代码重用：继承允许我们在新类中重用已有类的代码，避免重复编写相同的代码，提高开发效率。

可扩展性：通过继承，可以方便地扩展和修改已有的类，增强代码的灵活性和可维护性。

多态性：多态能使得同一个方法在不同子类里表现各不相同，让我们的程序在面对多种对象时能“同一接口、不同实现”。

结构清晰：通过在不同子类间的差异化，可以更清晰地表达相似事物的共同点与区别。

In [8]:
# 继承与方法重写示例

class Animal:
    def __init__(self,name):
        self.name = name
        
    def make_sound(self):
        print("动物发出声音。")

class Dog(Animal):
    def __init__(self, name, food):
        super().__init__(name)
        self.food = food
    def make_sound(self):
        print("狗汪汪叫。")

class Cat(Animal):
    def make_sound(self):
        print("猫喵喵叫。")
        
dog = Dog("TOM","肉")
cat = Cat("JERRY")

print(dog.food)
print(cat.name)
dog.make_sound()  # 输出：狗汪汪叫。
cat.make_sound()  # 输出：猫喵喵叫。



肉
JERRY
狗汪汪叫。
猫喵喵叫。


In [1]:
# 多态

# 动物基类
class Animal:
    def speak(self):
        print("动物都会叫，但叫声不同")

# 狗类
class Dog(Animal):
    def speak(self):
        print("狗：汪汪！")

# 猫类
class Cat(Animal):
    def speak(self):
        print("猫：喵喵~")

# 鸟类
class Bird(Animal):
    def speak(self):
        print("鸟：叽叽喳喳~")

# 定义一个统一调用的函数
def animal_speak(animal):
    animal.speak()

# 创建不同动物对象
dog = Dog()
cat = Cat()
bird = Bird()

animal_speak(dog)  
animal_speak(cat)   
animal_speak(bird) 


狗：汪汪！
猫：喵喵~
鸟：叽叽喳喳~


# 十一、模块与包的使用

代码复用：当你写完一个功能，如果别的项目也需要，就可以把它抽取出来放入自己的模块或包，随时调用，不必每次都拷贝粘贴。

维护方便：将不同功能放在不同的模块或包里，层次分明，一旦需要修改或扩展，就能聚焦于某个小范围的代码，而不必在成百上千行的混合代码里找出问题。

协同开发：在团队开发中，每个人负责不同模块或包，最后再整合，就能高效开发大型项目

## 11.1 模块

模块 指一个包含 Python 代码的文件（以 .py 结尾），里面可以定义函数、变量、类等。模块的主要作用是复用代码、组织项目结构，提高可读性和维护性。我们可以在同一目录下创建若干个 .py 文件，互相调用函数或类。

In [1]:
# use_module.py
import my_module

my_module.my_function()
print(my_module.PI)

这是模块中定义的一个函数
3.14159


In [2]:
# use_module.py
from my_module import PI

print(PI) # 可以不用带模块名

3.14159


In [3]:
from my_module import *

my_function() # 直接使用，不用带原模块名
print(PI)

这是模块中定义的一个函数
3.14159


## 11.2 包（package）

在 Python 中，包（Package） 是一种组织多个模块（Module） 的方式。它可以把多个相关的 Python 文件（模块） 组合在一起，形成一个层次化的结构，方便代码管理和复用。

当 Python 项目变得庞大时，仅仅使用模块（一个 .py 文件）会让项目结构变得杂乱。包提供了一种组织模块的方式，让多个模块可以按照文件夹（目录） 的方式进行管理。

In [5]:
import os
# 获取当前工作目录
print("当前工作目录:", os.getcwd())

# 列出目录内容
print("当前目录内容:", os.listdir("."))



# 检查路径是否存在
path = "my_module.py"
print(f"路径 {path} 是否存在:", os.path.exists(path))

# 判断是文件还是目录
if os.path.exists(path):
    print(f"{path} 是文件吗?", os.path.isfile(path))
    print(f"{path} 是目录吗?", os.path.isdir(path))

# 获取文件大小
if os.path.isfile(path):
    print(f"{path} 的大小:", os.path.getsize(path), "字节")

# 路径操作
file_path = "data/test.txt"
print("目录名:", os.path.dirname(file_path))
print("文件名:", os.path.basename(file_path))
print("文件扩展名:", os.path.splitext(file_path)[1])

# 路径拼接
new_path = os.path.join("data", "subfolder", "file.txt")
print("拼接路径:", new_path)

# 环境变量
print("PATH环境变量:", os.environ.get("PATH", "未设置")[:100] + "...")



当前工作目录: f:\PYTHON_TUTORIAL
当前目录内容: ['class1.ipynb', 'class2.ipynb', 'class3.ipynb', 'class4.ipynb', 'class5.ipynb', 'class6.ipynb', 'my_module.py', '__pycache__']
路径 my_module.py 是否存在: True
my_module.py 是文件吗? True
my_module.py 是目录吗? False
my_module.py 的大小: 143 字节
目录名: data
文件名: test.txt
文件扩展名: .txt
拼接路径: data\subfolder\file.txt
PATH环境变量: d:\Anaconda;D:\Anaconda;D:\Anaconda\Library\mingw-w64\bin;D:\Anaconda\Library\usr\bin;D:\Anaconda\Li...


# 十二、科学计算包Numpy

NumPy，作为 Numerical Python（数值 Python）或 Numeric Python（数值化 Python）的简称，是 Python 语言中用于科学计算的核心库 。它为 Python 提供了高性能的多维数组对象以及用于处理这些数组的工具。在科学、工程以及数据分析领域，NumPy 都扮演着至关重要的角色，是诸多高级库（如 Pandas、SciPy 和 Matplotlib）的基础 。

在数据科学日益重要的今天，高效地处理数值数据变得越来越关键。NumPy 正是为了解决这个问题而诞生的。它以其高性能和对大型数组进行高效存储与数据操作的能力而闻名 。尤其当处理规模庞大的数据集时，NumPy 数组在存储和处理效率上远超 Python 原生的列表。

NumPy 的核心概念是其 N 维数组，通常称为 ndarray 。ndarray 是一个由相同类型的元素组成的多维表格（通常是数字），这些元素通过一个由非负整数组成的元组进行索引 。在 NumPy 中，数组的维度被称为轴（axes）。例如，表示三维空间中一个点坐标的数组 [1, 2, 1] 就只有一个轴 。而一个二维数组，比如 [[0., 0., 0.], [1., 1., 1.]]，则有两个轴。第一个轴的长度是 2，第二个轴的长度是 3 。数组的秩（rank）指的是数组的维度数量 。数组的形状（shape）是一个整数元组，表示数组在每个维度上的大小 。NumPy 的 ndarray 类可以用来表示向量（一维数组）和矩阵（二维数组）。对于三维或更高维度的数组，通常使用术语张量（tensor）。


## 12.1 安装numpy

如果你的环境中还没有安装 NumPy，可以通过以下命令安装（建议在 Anaconda 环境中安装，已自带 NumPy）：

  ```bash
  pip install numpy

  conda install numpy

## 12.2 numpy三大核心属性
 
**1. 同质性**

同质性意味着数组中的所有元素都必须是相同的数据类型 。这使得 NumPy 可以在内存中以连续的方式存储数据，从而提高了访问和计算的效率。如果在创建数组时，提供的元素类型不一致，NumPy 会尝试将它们统一转换为一个更通用的类型 。例如，当你尝试创建一个包含整数和浮点数的数组时，NumPy 会将所有元素都转换为浮点数。

**2. 固定大小**

固定大小是指一旦 NumPy 数组被创建，其在内存中的大小就不能改变 。这与 Python 列表不同，列表是动态的，可以随时添加或删除元素。如果需要在 NumPy 数组中添加或删除元素，通常的做法是先将数组转换为 Python 列表，进行修改后再转换回 NumPy 数组，但这会带来额外的性能开销 。因此，在创建 NumPy 数组时，应该预先确定其大小。

**3. 固定形状**

形状（shape）是描述数组结构的关键属性。它是一个由整数组成的元组，每个整数表示数组在对应维度上的大小 。例如，一个包含 5 个元素的一维数组的形状是 (5,)。注意，形状元组中只有一个元素时，后面会有一个逗号，以区分它和普通的括号表达式。一个包含 2 行 3 列的二维数组的形状是 (2, 3) 。可以通过数组的 .shape 属性来获取其形状。

注意：在 NumPy 中，秩（Rank）和维度（ndim）是同一概念。在 NumPy 中，"秩" 这个词在非正式语境中通常指的是数组的维度 (ndim)。在线性代数中，矩阵的秩是指其线性无关的行或列的最大数目。

In [ ]:
import numpy as np
arr = np.array([1, 2.0, 3])
print(arr)
print(arr.dtype)
print(arr.shape)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)

## 12.3 使用特殊的数组创建函数

1. np.zeros()

此函数用于创建一个指定形状并用 0 填充的数组 。形状通过一个整数（用于一维数组）或一个整数元组（用于多维数组）来指定 。默认情况下，数组的数据类型是 float64 ，但可以通过 dtype 参数进行指定 。np.zeros() 常用于初始化数组、创建占位符或在算法中作为初始状态 。还有一个类似的函数 np.zeros_like(array)，它会创建一个与给定数组具有相同形状和数据类型的全零数组 。

2. np.ones()

与 np.zeros() 类似，但它创建的是一个指定形状并用 1 填充的数组 。形状的指定方式与 np.zeros() 相同，默认数据类型也是 float64 ，可以通过 dtype 参数修改 。np.ones() 常用于创建单位矩阵（结合 np.eye()）、初始化值为 1 的数组或在算法中作为初始条件 。同样，np.ones_like(array) 会创建一个与给定数组具有相同形状和数据类型的全 1 数组 。


In [13]:
import numpy as np

# 创建一个包含 5 个浮点数 0 的一维数组
zeros_arr1 = np.zeros(5)
print(f"一维数组：\n{zeros_arr1}")

# 创建一个 2x3 的整数 0 填充的二维数组
zeros_arr2 = np.zeros((2, 3), dtype=int)
print(f"二维数组：\n{zeros_arr2}")

# 基于现有数组的形状和类型创建一个全零数组
existing_arr = np.array([[1, 2], [3, 4]])
zeros_like_arr = np.zeros_like(existing_arr)
print(f"与现有数组形状相同的全零数组：\n{zeros_like_arr}")

一维数组：
[0. 0. 0. 0. 0.]
二维数组：
[[0 0 0]
 [0 0 0]]
与现有数组形状相同的全零数组：
[[0 0]
 [0 0]]


In [14]:
# 创建一个包含 3 个浮点数 1 的一维数组
ones_arr1 = np.ones(3)
print(f"一维数组：\n{ones_arr1}")

# 创建一个 2x2 的整数 1 填充的二维数组
ones_arr2 = np.ones((2, 2), dtype=int)
print(f"二维数组：\n{ones_arr2}")

# 基于现有数组的形状和类型创建一个全 1 数组
existing_arr = np.array([[1, 2], [3, 4]])
ones_like_arr = np.ones_like(existing_arr)
print(f"与现有数组形状相同的全 1 数组：\n{ones_like_arr}")

一维数组：
[1. 1. 1.]
二维数组：
[[1 1]
 [1 1]]
与现有数组形状相同的全 1 数组：
[[1 1]
 [1 1]]


3. np.fill()

创建一个指定形状并用给定的值填充的数组 。需要提供形状（shape）和一个填充值（fill_value）作为参数 。数据类型会根据填充值自动推断，但也可以通过dtype 参数显式指定 。np.full_like(array, fill_value) 则创建一个与给定数组具有相同形状和数据类型的，并用指定值填充的数组 。

4. np.empty()

创建一个指定形状的数组，但其初始内容是随机的，取决于内存的状态 。使用 np.empty() 而不是 np.zeros()（或 np.ones()) 的主要原因是速度，因为它不会初始化数组元素 。但是，在使用之前务必确保填充数组中的每个元素 。可以通过 dtype 参数指定数据类型 。

5. np.arange()

这个函数返回一个在给定间隔内均匀分布的值组成的数组 。可以指定起始值（start，默认为 0）、停止值（stop，必需）和步长（step，默认为 1）。需要注意的是，返回的数组不包含停止值 。

In [15]:
import numpy as np

# 创建一个 2x4 的未初始化数组
empty_arr = np.empty((2, 4))
print(f"未初始化数组:\n{empty_arr}")

import numpy as np

# 创建一个 3x3 的数组，所有元素都填充为 7
full_arr1 = np.full((3, 3), 7)
print(full_arr1)

# 创建一个与现有数组形状和类型相同的，所有元素都填充为 3.14 的数组
existing_arr = np.array([[1.0, 2], [3, 4]])
full_like_arr = np.full_like(existing_arr, 3.14)
print(full_like_arr)

未初始化数组:
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.80623720e-321 8.45603440e-307 4.45046007e-307]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[3.14 3.14]
 [3.14 3.14]]


In [16]:
import numpy as np

# 创建一个从 0 到 4 的整数数组（步长为默认值 1）
arange_arr1 = np.arange(5)
print(arange_arr1)

# 创建一个从 2 到 9 的整数数组（步长为 2）
arange_arr2 = np.arange(2, 10, 2)
print(arange_arr2)

# 创建一个从 0 到接近 2 的浮点数数组（步长为 0.3）
arange_arr3 = np.arange(0, 2, 0.3)
print(arange_arr3)


[0 1 2 3 4]
[2 4 6 8]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


| 函数 | 描述 | 示例 |
| --- | --- | --- |
| np.array() | 从列表或元组创建数组。 | np.array([1, 2, 3, 4]), np.array((5, 6, 7, 8)) |
| np.zeros() | 创建一个填充为零的数组。 | np.zeros((2, 3)) |
| np.ones() | 创建一个填充为一的数组。 | np.ones((2, 3)) |
| np.empty() | 创建一个未初始化的数组。 | np.empty((2, 3)) |
| np.full() | 创建一个用特定值填充的数组。 | np.full((2, 3), 5) |
| np.arange() | 创建一个在给定范围内均匀分布的值组成的数组。 | np.arange(0, 10, 2) |
| np.linspace() | 创建一个在给定范围内指定数量的均匀间隔的值组成的数组。 | np.linspace(0, 10, 5) |
| np.eye() | 创建一个单位矩阵。 | np.eye(3) |
| np.diag() | 创建一个对角矩阵或提取数组的对角线。 | np.diag([1, 2, 3]), np.diag(np.array([[1, 2], [3, 4]])) |
| np.zeros_like() | 创建一个与给定数组具有相同形状和类型的全零数组。 | np.zeros_like(np.array([[1, 2], [3, 4]])) |
| np.ones_like() | 创建一个与给定数组具有相同形状和类型的全一数组。 | np.ones_like(np.array([[1, 2], [3, 4]])) |
| np.full_like() | 创建一个与给定数组具有相同形状和类型的，并用指定值填充的数组。 | np.full_like(np.array([[1, 2], [3, 4]]), 7) |

## 12.4 数组索引与切片

与 Python 的列表类似，NumPy 数组支持索引和切片操作。但由于其支持多维，因此操作更为灵活。

1. 基本索引
 
NumPy 数组的索引是从 0 开始的，这意味着数组中的第一个元素的索引是0。对于一维数组，可以使用方括号 [] 加上索引来访问单个元素，这与 Python 列表的索引方式类似。对于多维数组，需要使用一个由逗号分隔的索引元组来访问元素，每个索引对应一个维度。

In [17]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 输出第一个元素
print(arr[-1]) # 输出最后一个元素（负索引也适用）

# 创建一个 3 维数组
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# 使用逗号分隔的方式访问元素
print(arr_3d[0, 1, 1]) 

# 使用元组形式访问元素
print(arr_3d[(1, 0, 1)])  


10
50
4
6


2. 切片

切片用于获取数组的一个子集（subarray）。切片的语法是 [start:stop:step]，其中 start 是起始索引（包含），stop 是结束索引（不包含），step 是步长（默认为 1）。对于一维数组，切片操作与Python列表类似。对于多维数组，可以对每个维度应用切片，并用逗号分隔。

In [18]:
import numpy as np

arr = np.arange(10)  # 创建一个从 0 到 9 的一维数组
print(f"输出索引 2、3、4 的元素: {arr[2:5]}") 
print(f"输出从开始到索引 2 的元素：{arr[:3]}")     
print(f"输出从索引 5 到结束的元素：{arr[5:]}")     
print(f"输出所有索引为偶数的元素：{arr[::2]}")  
print(f"反转数组：{arr[::-1]}") 

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"二维数组：\n{arr_2d}")
print(f"输出前两行（索引 0 和 1)，以及从第二列（索引 1)到结束的所有列的元素：\n{arr_2d[:2, 1:]}") 
print(f"输出第二行所有元素：\n{arr_2d[1, :]}") 
print(f"输出第一列所有元素：\n{arr_2d[:, 0]}") 

输出索引 2、3、4 的元素: [2 3 4]
输出从开始到索引 2 的元素：[0 1 2]
输出从索引 5 到结束的元素：[5 6 7 8 9]
输出所有索引为偶数的元素：[0 2 4 6 8]
反转数组：[9 8 7 6 5 4 3 2 1 0]
二维数组：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
输出前两行（索引 0 和 1)，以及从第二列（索引 1)到结束的所有列的元素：
[[2 3]
 [5 6]]
输出第二行所有元素：
[4 5 6]
输出第一列所有元素：
[1 4 7]


3. 布尔索引

布尔索引允许我们根据条件选择数组中的元素 。我们可以创建一个与原始数组形状相同的布尔数组，其中 True 对应的位置的元素会被选中，False 对应的元素则不会。多个条件可以使用逻辑运算符 &（与）和 |（或）组合起来。

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2  # 创建一个布尔数组，标记大于 2 的元素
print(mask)
print(arr[mask]) # 使用布尔数组作为索引来选择元素

# 也可以直接在索引中使用条件表达式
print(arr[arr % 2 == 0]) # 选择所有偶数元素

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[(arr > 1) & (arr < 5)]) # 选择大于 1 且小于 5 的元素
print(arr[(arr % 2 == 0) | (arr % 3 == 0)]) # 选择是偶数或能被 3 整除的元素


[False False  True  True  True]
[3 4 5]
[2 4]
[2 3 4]
[2 3 4 6]


4. 整数数组索引

整数数组索引允许我们使用整数数组来选择原始数组中的元素 。返回的数组的形状将与索引数组的形状相匹配。整数数组索引提供了一种非常灵活的方式来选择数组中的特定元素，即使这些元素不是连续的。

In [20]:
import numpy as np
# 一维数组示例
arr = np.array([1, 2, 3, 4, 5, 6])
indices = np.array([1, 3, 4])  # 想要选择索引为1,3,4的元素
print("根据indices选择:", arr[indices])

# 二维数组示例
arr_2d = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
row_indices = np.array([0, 2])  # 指定要选择第0行和第2行
col_indices = np.array([1, 0])  # 指定要选择第1列和第0列
print("根据row_indices, col_indices选择:", arr_2d[row_indices, col_indices])

根据indices选择: [2 4 5]
根据row_indices, col_indices选择: [2 5]


# 十三、文件操作

## 13.1 文件类型

1.文本文件：存储可读的字符数据，如 .txt、.csv、.json、.xml 等。

2.二进制文件：存储非字符数据，如图片、音频、视频、可执行文件等。

## 13.2 文件路径：

1.绝对路径：是指从系统根目录（Windows: C:\，Linux/macOS: /）开始，完整地指定文件或文件夹的位置，无论当前在哪个目录，都能唯一确定该文件的位置。如 /home/user/documents/data.txt。

2.相对路径：指相对于当前工作目录（程序运行的起点）来指定文件或文件夹的位置，而不是从系统根目录开始。比如./data.txt代表当前目录下的data.txt。../config/settings.json代表上一级目录的 config 文件夹内 settings.json。

## 13.3 文件模式：

1.读取模式 ('r')：只读模式，文件必须存在，否则报错。

2.写入模式 ('w')：写入模式，会清空原文件内容；如果文件不存在，会创建新文件。

3.追加模式 ('a')：在文件末尾追加内容，不会清空原内容；文件不存在时会创建新文件。

4.二进制模式 ('b')：用于处理图片、音频、视频等非文本文件，可以与其他模式组合使用，如 'rb'（二进制读取）、'wb'（二进制写入）。

5.读写模式 ('r+', 'w+', 'a+')'r+'：同时读+写，不会清空文件，文件必须存在。'w+'：同时写+读，但会清空原文件，文件不存在时会创建。'a+'：同时追加+读，不会清空文件，文件不存在时会创建。

## 13.4 文件编码：

1.UTF-8（默认编码）：支持多种语言字符，通用且推荐使用。

2.GBK：适用于简体中文文件，部分旧系统仍在使用。

3.ASCII：只支持英文和基本符号，无法存储中文。

In [2]:
#文件的打开与关闭

with open('目录.ipynb', 'r', encoding='utf-8') as file:  # 读取一个文本文件
    lines = file.readlines()  # 读取文件
    print(lines)



['{\n', ' "cells": [\n', '  {\n', '   "cell_type": "markdown",\n', '   "metadata": {},\n', '   "source": [\n', '    "1.\\t变量\\n",\n', '    "\\n",\n', '    "2.\\t常见数据类型\\n",\n', '    "\\n",\n', '    "3.\\t可变与不可变类型\\n",\n', '    "\\n",\n', '    "4.\\t运算符\\n",\n', '    "\\n",\n', '    "5.\\t列表和元组\\n",\n', '    "\\n",\n', '    "6.\\t条件表达式与布尔值\\n",\n', '    "\\n",\n', '    "7.\\t循环结构和循环控制语句\\n",\n', '    "\\n",\n', '    "8.\\t函数\\n",\n', '    "\\n",\n', '    "9.\\t字典\\n",\n', '    "\\n",\n', '    "10.\\t类与对象、属性、方法、构造函数\\n",\n', '    "\\n",\n', '    "11.\\t模块与包\\n",\n', '    "\\n"\n', '   ]\n', '  }\n', ' ],\n', ' "metadata": {\n', '  "language_info": {\n', '   "name": "python"\n', '  }\n', ' },\n', ' "nbformat": 4,\n', ' "nbformat_minor": 2\n', '}\n']


确认文件是否存在，可以用 os.path.exists() 先检查,os.path.exists() 方法可以检查给定路径的文件是否存在。

In [5]:
import os
if not os.path.exists("test.txt"):

    print("文件不存在")


def copy_file(source, destination):
    with open(source, "r", encoding="utf-8") as src:
        content = src.read()

    with open(destination, "w", encoding="utf-8") as dst:
        dst.write(content)

# 使用
copy_file("test.txt", "copy.txt")

# 十四、矩阵操作

## 常见的矩阵数据运算
| 函数名称            | 描述                                              |
|---------------------|---------------------------------------------------|
| np.sin( )            | 对数组中的每个元素执行正弦运算                    |
| np.cos( )            | 对数组中的每个元素执行余弦运算                    |
| np.tan( )            | 对数组中的每个元素执行正切运算                    |
| np.exp( )            | 对数组中的每个元素执行指数运算                    |
| np.log()            | 对数组中的每个元素执行自然对数运算                |
| np.log10( )          | 对数组中的每个元素执行以 10 为底的对数运算         |
| np.sqrt( )           | 对数组中的每个元素执行平方根运算                  |
| np.abs( )            | 对数组中的每个元素执行绝对值运算                  |
| np.round( )          | 将数组中的每个元素四舍五入到最接近的整数          |
| np.floor( )          | 返回不大于数组中每个元素的 floor 值（向下取整到最接近的整数）|
| np.ceil( )           | 返回不小于数组中每个元素的 ceil 值（向上取整到最接近的整数）|
| np.power(arr, n)    | 对数组 arr 的每个元素执行 n 次幂运算              |

## 14.1 矩阵逐元素加减乘除


In [1]:
import numpy as np
 
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
 
# 矩阵加法
C = A + B
print("矩阵加法:\n", C)
 
# 矩阵减法
D = A - B
print("矩阵减法:\n", D)
 
# 矩阵逐元素乘法
element_wise_product = A * B
print("逐元素乘法:\n", element_wise_product)
 
# 矩阵逐元素除法
element_wise_divide = A / B
print("逐元素除法结果:\n", element_wise_divide)

矩阵加法:
 [[ 6  8]
 [10 12]]
矩阵减法:
 [[-4 -4]
 [-4 -4]]
逐元素乘法:
 [[ 5 12]
 [21 32]]
逐元素除法结果:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 14.2 矩阵乘法

1. 矩阵点乘：矩阵对应元素相乘（形状相同）np.multiply(a,b) 或a*b

2. 矩阵叉乘（矩阵相乘）：np.dot(a,b)或a@b

3. 向量点乘（向量内积）：np.dot(a,b)或a@b，为标量

4. 向量逐元素相乘：np.multiply(a,b)等价于a*b

5. 向量外积（向量积或叉积）：np.cross(a,b)两个向量的法向量

         

In [9]:
import numpy as np
 
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([1, 2, 3])
D = np.array([5, 6, 7])
 
# 矩阵点乘/矩阵逐元素相乘
E = A * B
F = np.multiply(A, B)
print("矩阵点乘：\n", E)
 
 
# 矩阵相乘/矩阵叉乘
G = A @ B
H = np.dot(A, B)
print("矩阵叉乘：\n", G)
 
# 向量点乘/向量内积
J = C @ D
K = np.dot(C, D)
print("向量点乘：\n", J)
 
# 向量逐元素相乘
L = C * D
M = np.multiply(C, D)
print("向量逐元素相乘：\n", L)
 
# 向量外积、向量积或叉积，向量的法向量
N = np.cross(C, D)
print("向量外积：", N)

矩阵点乘：
 [[ 5 12]
 [21 32]]
矩阵叉乘：
 [[19 22]
 [43 50]]
向量点乘：
 38
向量逐元素相乘：
 [ 5 12 21]
向量外积： [-4  8 -4]


## 14.3 矩阵属性计算

1. 矩阵转置：矩阵的转置是将矩阵的行和列互换，使用 .T 属性。

2. 矩阵的逆：矩阵的逆对方阵（行数与列数相同的矩阵）定义，使用 numpy.linalg.inv() 可以计算矩阵的逆。

3. 矩阵的行列式：行列式是标量值，表示矩阵的某些属性（如是否可逆）。使用 numpy.linalg.det() 可以计算矩阵的行列式。

4. 矩阵的迹：矩阵的迹是矩阵主对角线上元素的和，使用 numpy.trace() 可以计算。

5. 矩阵的特征值和特征向量：特征值和特征向量是矩阵的重要属性。你可以使用 numpy.linalg.eig() 函数来计算特征值和特征向量。

6. 矩阵的广义逆：广义逆矩阵（Moore-Penrose伪逆）用于非方阵或不可逆的矩阵。使用 numpy.linalg.pinv() 计算矩阵的广义逆。

7. 矩阵的范数：矩阵的范数用于度量矩阵的大小。可以使用 numpy.linalg.norm() 计算不同类型的范数。


In [10]:
import numpy as np
 
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
 
# 矩阵转置
A_T = A.T
print("矩阵转置:\n", A_T)
 
# 矩阵的逆
A_inv = np.linalg.inv(A)
print("矩阵的逆:\n", A_inv)
 
# 矩阵的行列式
det_A = np.linalg.det(A)
print("矩阵行列式:\n", det_A)
 
# 矩阵的迹
trace_A = np.trace(A)
print("矩阵的迹:\n", trace_A)
 
# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)
print("特征值:\n", eigenvalues)
print("特征向量:\n", eigenvectors)
 
# 计算广义逆矩阵
pseudo_inv = np.linalg.pinv(A)
print("广义逆矩阵:\n", pseudo_inv)
 
 
# 计算矩阵的二范数（默认）
norm_A = np.linalg.norm(A)
print("矩阵的二范数:\n", norm_A)
 
# 计算矩阵的 1 范数（列和的最大值）
norm_A_1 = np.linalg.norm(A, ord=1)
print("矩阵的 1 范数:\n", norm_A_1)
 
# 计算矩阵的无穷范数（行和的最大值）
norm_A_inf = np.linalg.norm(A, ord=np.inf)
print("矩阵的无穷范数:\n", norm_A_inf)


矩阵转置:
 [[1 3]
 [2 4]]
矩阵的逆:
 [[-2.   1. ]
 [ 1.5 -0.5]]
矩阵行列式:
 -2.0000000000000004
矩阵的迹:
 5
特征值:
 [-0.37228132  5.37228132]
特征向量:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
广义逆矩阵:
 [[-2.   1. ]
 [ 1.5 -0.5]]
矩阵的二范数:
 5.477225575051661
矩阵的 1 范数:
 6.0
矩阵的无穷范数:
 7.0


## 14.4 解3 × 3 线性方程组


考虑线性方程组：

$$
\begin{cases}
x + 2y + 3z = 1 \\
4x + 5y + 6z = 2 \\
7x + 4y + 3z = 3
\end{cases}
$$

对应的矩阵形式为：

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 4 & 3 \end{bmatrix}
$$

$$
B = \begin{bmatrix}
1  \\
2  \\
3
\end{bmatrix}
$$

In [11]:
import numpy as np
 
# 系数矩阵 A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 4, 3]])
 
# 结果向量 B
B = np.array([1, 2, 3])
 
# 求解线性方程组
X = np.linalg.solve(A, B)
print("解:\n", X)


解:
 [ 1.         -2.          1.33333333]



# 作业：学生管理系统

## 问题描述

## 设计一个简单的学生管理系统，能够完成以下功能：

•	添加学生信息（包括姓名、年龄、学号）

•	删除学生信息

•	查询学生信息（通过学号查询）

•	显示所有学生信息
